[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.47.0",
    "python-dotenv>=1.0.0",
    "google-generativeai>=0.4.1"

]
